### ISSUE TITLE
Don't run example

### ISSUE THREAD

**Issue by ghost** [k-kinzal/dgeni-markdown-example#1]
example don't working

D:\project\dgeni-markdown-example>grunt
Running "dgeni" task
error:   Error processing docs:  TypeError: object is not a function
    at Function.v.extend.async (D:\project\dgeni-markdown-example\node_modules\g
runt-dgeni\node_modules\dgeni\node_modules\validate.js\validate.js:196:14)
    at D:\project\dgeni-markdown-example\node_modules\grunt-dgeni\node_modules\d
geni\lib\Dgeni.js:166:23
    at _fulfilled (D:\project\dgeni-markdown-example\node_modules\grunt-dgeni\no
de_modules\dgeni\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\project\dgeni-markdown-example\node_modules
\grunt-dgeni\node_modules\dgeni\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\project\dgeni-markdown-example\node_m
odules\grunt-dgeni\node_modules\dgeni\node_modules\q\q.js:796:13)
    at D:\project\dgeni-markdown-example\node_modules\grunt-dgeni\node_modules\d
geni\node_modules\q\q.js:857:14
    at runSingle (D:\project\dgeni-markdown-example\node_modules\grunt-dgeni\nod
e_modules\dgeni\node_modules\q\q.js:137:13)
    at flush (D:\project\dgeni-markdown-example\node_modules\grunt-dgeni\node_mo
dules\dgeni\node_modules\q\q.js:125:13)
    at process._tickCallback (node.js:442:13)
    at Function.Module.runMain (module.js:499:11)

D:\project\dgeni-markdown-example>node -v
v0.10.35

D:\project\dgeni-markdown-example>npm -v
1.4.28

**Comment by k-kinzal** [comment]
@neborskiyA 
https://github.com/angular/dgeni/blob/master/.travis.yml#L2-L4
Dgeni support Node v4 or v5. please upgrade Node and run.

**Comment by ghost** [comment]
Thanks!
